# Global run config for AWS 1,2,4,8 GPUs: Instance 1
cloud_type: aws

tf_url: tensorflow-gpu

instance_tag: tf-single1
instance_type: p2.8xlarge
instance_ami: ami-xxxxxxx  # cuDNN 6
instance_force_reuse: False
instance_on_finish: start
instance_count: 1
gpus: '1,2,4,8'
batch_size: 64
# Local
gobal_on_finish: stop
repeat: 5
data_dir: '/home/ubuntu/efs/imagenet-data'
efs: ['']
